version: 2.1

jobs:
  container:
    image: apon77/aosp:cirrus
    resource_class: large

   Storage_Checker:
    - df -h
    - lsblk
    - ls -l -a -h

  Sync_script:
    - bash sync.sh

  Build_script:
    - bash build.sh

  Upload_script:
    - export TIMEOUT=43200 # Download Link Timeout (in Minutes)
    - bash upload.sh
