version: 2.1

jobs:
  container:
    image: apon77/aosp:cirrus
    resource_class: large

  steps:
      - checkout
      - run:
          name: Sync
          command: |
            bash sync.sh
      - run:
          name: Build
          command: |
            bash build.sh
      - run:
          name: Upload
          command: |
            export TIMEOUT=43200
            bash upload.sh
