version: 2.1

jobs:
  container:
    image: apon77/aosp:cirrus
    resource_class: large

  Sync_script:
    - bash sync.sh

  Build_script:
    - bash build.sh

  Upload_script:
    - export TIMEOUT=43200 # Download Link Timeout (in Minutes)
    - bash upload.sh
